---
# tasks file for yaourt

- name: Create AUR temporary directory
  file:
    path: "{{ yaourt_tmp_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0777
  become: true

- name: If necessary, install git
  pacman:
    name: git
    state: present
  when: yaourt_use_git
  become: true

- name: Install yajl
  pacman:
    name: yajl
    state: present
  become: true

- name: Install package-query and yaourt from AUR
  include_role:
    name: jtyr.archlinux_aur
  vars:
    archlinux_aur_pkgs:
      - "package-query"
      - "yaourt"
  become: true

- name: Add yaourt configuration
  template:
    src: yaourtrc.j2
    dest: /etc/yaourtrc
    owner: root
    group : root
    mode: 0644
  become: true
