---
# tasks file for xorg

- name: Install xorg-server, apps, drivers, and fonts
  yaourt:
    name: "{{ item }}"
    state: present
  with_items:
    - xorg-server
    - xorg-apps
    - xorg-xinit
    - xorg-fonts-misc
    - "{{ xorg_pkg_video_driver }}"
    - "{{ xorg_pkg_input_driver }}"
    - ttf-google-fonts-git
    - cantarell-fonts
    - gsfonts-type1
    - tex-gyre-fonts
    - ttf-caladea
    - ttf-carlito
    - ttf-courier-prime
    - ttf-dejavu-ib
    - ttf-heuristica
    - ttf-impallari-cantora
    - ttf-liberation
    - ttf-symbola-ib
    - fonts-meta-base
    - fonts-meta-extended-lt

- name: Link font configurations
  file:
    src: "/etc/fonts/conf.avail/{{ item }}"
    dest: "/etc/fonts/conf.d/{{ item }}"
    state: link
  with_items:
    - 10-hinting-slight.conf
    - 10-sub-pixel-rgb.conf
    - 11-lcdfilter-default.conf
  become: true

- name: Copy Xwrapper.config
  copy:
    src: Xwrapper.config
    dest: /etc/X11/Xwrapper.config
    owner: root
    group: root
    mode:  0644
  become: true

